/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.ifsp.view;

import com.ifsp.controller.ClientController;
import com.ifsp.dao.DB;
import com.ifsp.controller.UserController;
import java.sql.*;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import com.ifsp.model.Client;
import com.ifsp.service.ClientService;
import com.ifsp.util.Mask;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class FrameClient extends javax.swing.JInternalFrame {

    Connection connection = null;
    PreparedStatement pst = null;
    ResultSet rst = null;
    List<Client> clientsList;
    DefaultTableModel model;

    Client client = new Client();
    Client clientNew = client;
    Client clientUpdate = client;
    boolean isUpdate = false;

    /**
     * Creates new form FrameClient
     */
    public FrameClient() {
        initComponents();

        connection = DB.connect();

        Mask.applayMaskProne(txfPhone);
        Mask.applayMaskCpf(txfCpf);

        listClientsInTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabClientData = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        txfAddres = new javax.swing.JTextField();
        txfPhone = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        txfCpf = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txfName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txfEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txfId = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnClientDelete = new javax.swing.JButton();
        btnClientClear = new javax.swing.JButton();
        btnClientCreate = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txfTermSearch = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Gestão de Clientes");
        setMaximumSize(new java.awt.Dimension(143, 22));
        setMinimumSize(new java.awt.Dimension(143, 22));
        setPreferredSize(new java.awt.Dimension(750, 533));

        jScrollPane1.setToolTipText("");

        tabClientData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NOME", "CPF", "E-MAIL", "PHONE", "ENDEREÇO"
            }
        ));
        tabClientData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabClientDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabClientData);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 205));

        jLabel6.setText("CPF");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add.png"))); // NOI18N
        jLabel1.setText("Dados do Cliente");

        jLabel2.setText("Nome");

        jLabel3.setText("E-mail");

        jLabel4.setText("WhatsApp");

        jLabel5.setText("Endereço");

        txfId.setEditable(false);
        txfId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfId.setEnabled(false);
        txfId.setFocusable(false);

        jLabel7.setText("ID");

        btnClientDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bin.png"))); // NOI18N
        btnClientDelete.setText("Excluir");
        btnClientDelete.setToolTipText("");
        btnClientDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnClientDelete.setMaximumSize(new java.awt.Dimension(50, 50));
        btnClientDelete.setMinimumSize(new java.awt.Dimension(45, 45));
        btnClientDelete.setPreferredSize(new java.awt.Dimension(45, 45));
        btnClientDelete.addActionListener(this::btnClientDeleteActionPerformed);

        btnClientClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/refresh.png"))); // NOI18N
        btnClientClear.setText("Resetar");
        btnClientClear.setToolTipText("");
        btnClientClear.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnClientClear.setMaximumSize(new java.awt.Dimension(50, 50));
        btnClientClear.setMinimumSize(new java.awt.Dimension(45, 45));
        btnClientClear.setPreferredSize(new java.awt.Dimension(45, 45));
        btnClientClear.addActionListener(this::btnClientClearActionPerformed);

        btnClientCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add.png"))); // NOI18N
        btnClientCreate.setText("Salvar");
        btnClientCreate.setToolTipText("");
        btnClientCreate.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnClientCreate.setMaximumSize(new java.awt.Dimension(50, 50));
        btnClientCreate.setMinimumSize(new java.awt.Dimension(45, 45));
        btnClientCreate.setPreferredSize(new java.awt.Dimension(45, 45));
        btnClientCreate.addActionListener(this::btnClientCreateActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(txfPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnClientCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnClientDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnClientClear, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txfAddres)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(12, 12, 12)
                                    .addComponent(jLabel7)
                                    .addGap(35, 35, 35))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(txfId, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(txfName, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(txfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(txfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7))
                        .addGap(36, 36, 36))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txfName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txfId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txfPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, 0)
                        .addComponent(txfAddres, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnClientDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(btnClientClear, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClientCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search.png"))); // NOI18N
        jLabel8.setText("Pesquisar");

        txfTermSearch.setText("Pesquisar");
        txfTermSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txfTermSearchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txfTermSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txfTermSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 726, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listClientsInTable() {
        clientsList = new ArrayList<>();

        model = (DefaultTableModel) tabClientData.getModel();
        model.setNumRows(0);
        model.setColumnIdentifiers(new Object[]{"ID", "NOME", "CPF", "E-MAIL", "WHATSAPP", "ENDEREÇO"});

        clientsList = new ClientController().list();

        if (clientsList.size() > 0) {
            for (Client c : clientsList) {
                model.addRow(new Object[]{
                    c.getId(),
                    c.getName(),
                    Mask.maskCpf(c.getCpf()),
                    c.getEmail(),
                    Mask.maskPhone(c.getPhone()),
                    c.getAddress()
                });
                System.out.println("Usuario: " + c.toString());
            }
        }
    }

    private void setFormWithDataSelected() {
        int row = tabClientData.getSelectedRow();

        clientUpdate = new Client();
        
        clientUpdate.setId((int) tabClientData.getModel().getValueAt(row, 0));

        txfId.setText(tabClientData.getModel().getValueAt(row, 0).toString());
        txfName.setText(tabClientData.getModel().getValueAt(row, 1).toString());
        txfCpf.setText(tabClientData.getModel().getValueAt(row, 2).toString());
        txfEmail.setText(tabClientData.getModel().getValueAt(row, 3).toString());
        txfPhone.setText(tabClientData.getModel().getValueAt(row, 4).toString());
        txfAddres.setText(tabClientData.getModel().getValueAt(row, 5).toString());

    }

    private void cleanAndResetForm() {
        txfName.setText("");
        txfEmail.setText("");
        txfPhone.setText("");
        txfAddres.setText("");
        txfCpf.setText("");
        txfId.setText("");

        // limpa dados de atulização
        isUpdate = false;

        // ajusta o botão da salvar
        btnClientCreate.setIcon(
                new javax.swing.ImageIcon(
                        getClass().getResource("/icons/add.png")
                )
        );
    }

    private void updateTableWithSearch(String str) {

        clientsList = new ClientController().searchByName(str);

        if (clientsList.size() > 0) {

            model.setNumRows(0);

            for (Client c : clientsList) {

                System.out.println("Pesrquisa: " + c.getName());

                model.addRow(new Object[]{
                    c.getId(),
                    c.getName(),
                    c.getCpf(),
                    c.getEmail(),
                    c.getPhone(),
                    c.getAddress()
                }
                );
            }
        }
    }

    private void txfTermSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfTermSearchKeyReleased
        // TODO add your handling code here:
        String str = txfTermSearch.getText();

        System.out.println("Change: " + str);

        if (str.length() > 3) {
            updateTableWithSearch(str);
        } else if (!str.isEmpty() || !str.isBlank()) {
            listClientsInTable();
        }
    }//GEN-LAST:event_txfTermSearchKeyReleased

    private void tabClientDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabClientDataMouseClicked
        // TODO add your handling code here:
        setFormWithDataSelected();
        isUpdate = true;

        btnClientCreate.setIcon(
                new javax.swing.ImageIcon(
                        getClass().getResource("/icons/edit.png")
                )
        );
    }//GEN-LAST:event_tabClientDataMouseClicked

    private void btnClientCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientCreateActionPerformed

        Client client = new Client();

        if (isUpdate) {
            client.setId(clientUpdate.getId());
        }
        client.setName(txfName.getText());
        client.setCpf(txfCpf.getText().replaceAll("[^0-9]", ""));
        client.setEmail(txfEmail.getText());
        client.setPhone(txfPhone.getText().replaceAll("[^0-9]", ""));
        client.setAddress(txfAddres.getText());

        ClientService service = new ClientService();
        String result = service.saveClient(client);

        if (result.equals("SUCESSO")) {
            JOptionPane.showMessageDialog(this, "Cliente salvo com sucesso!");
            cleanAndResetForm();
            listClientsInTable();
        } else {
            JOptionPane.showMessageDialog(this, result, "Erro de Validação", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnClientCreateActionPerformed

    private void btnClientClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientClearActionPerformed
        // TODO add your handling code here:
        cleanAndResetForm();

        listClientsInTable();
    }//GEN-LAST:event_btnClientClearActionPerformed

    private void btnClientDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientDeleteActionPerformed
        // TODO add your handling code here:

        //        if (user == null) {
            //            JOptionPane.showMessageDialog(this, "Precisa fazer a busca do regstro para excluir.", "Aviso", JOptionPane.ERROR_MESSAGE);
            //            return;
            //        }
        //
        //        //        Object[] options = {"Sim", "Cancelar"};
        //        //        null,
        //        //        options,
        //        //        options[1]
        //        int option = JOptionPane.showConfirmDialog(
            //            this,
            //            "Deseja excluir o registro?",
            //            "Confirmar exclusão",
            //            JOptionPane.OK_CANCEL_OPTION,
            //            JOptionPane.QUESTION_MESSAGE
            //        );
        //
        //        if (option != JOptionPane.YES_OPTION) {
            //            return;
            //        }
        //
        //        if (new UserController().deleteUser(user.getId())) {
            //            JOptionPane.showMessageDialog(this, "Registro excluido com sucesso!");
            //            clearForm();
            //        } else {
            //            JOptionPane.showMessageDialog(this, "Nenhum registro encontrado com esse ID.");
            //        }
    }//GEN-LAST:event_btnClientDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClientClear;
    private javax.swing.JButton btnClientCreate;
    private javax.swing.JButton btnClientDelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabClientData;
    private javax.swing.JTextField txfAddres;
    private javax.swing.JFormattedTextField txfCpf;
    private javax.swing.JTextField txfEmail;
    private javax.swing.JTextField txfId;
    private javax.swing.JTextField txfName;
    private javax.swing.JFormattedTextField txfPhone;
    private javax.swing.JTextField txfTermSearch;
    // End of variables declaration//GEN-END:variables
}
