package com.ifsp.view;

import com.ifsp.dao.DB;
import com.ifsp.controller.UserController;
import java.sql.*;
import javax.swing.JOptionPane;
import com.ifsp.model.User;
import com.ifsp.service.UserService;
import com.ifsp.util.Mask;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class FrameUser extends javax.swing.JInternalFrame {

    Connection connection = null;
    PreparedStatement pst = null;
    ResultSet rst = null;
    List<User> usersList;
    DefaultTableModel model;

    User user = new User();
    User userNew = user;
    User userUpdate = user;
    boolean isUpdate = false;

    public FrameUser() {
        initComponents();

        connection = DB.connect();

        Mask.applayMaskProne(txfPhone);

        listClientsInTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txfName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txfEmail = new javax.swing.JTextField();
        cbxPermission = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        txfPhone = new javax.swing.JFormattedTextField();
        btnUserDelete = new javax.swing.JButton();
        btnUserClear = new javax.swing.JButton();
        btnUserCreate = new javax.swing.JButton();
        btnUserReset = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txfId = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txfPassword = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        txfPasswordConfirm = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDataUser = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txfTermSearch = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Gestão de Usuários");
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(750, 533));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/people.png"))); // NOI18N
        jLabel1.setText("DADOS DO USUÁRIO");

        jLabel2.setText("ID");

        jLabel4.setText("Usuário");

        cbxPermission.setText("Admin/Editor?");

        jLabel5.setText("WhatsApp");

        btnUserDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bin.png"))); // NOI18N
        btnUserDelete.setText("Excluir");
        btnUserDelete.setToolTipText("");
        btnUserDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnUserDelete.setPreferredSize(new java.awt.Dimension(45, 45));
        btnUserDelete.addActionListener(this::btnUserDeleteActionPerformed);

        btnUserClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/refresh.png"))); // NOI18N
        btnUserClear.setToolTipText("");
        btnUserClear.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnUserClear.setPreferredSize(new java.awt.Dimension(45, 45));
        btnUserClear.addActionListener(this::btnUserClearActionPerformed);

        btnUserCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add.png"))); // NOI18N
        btnUserCreate.setText("Salva");
        btnUserCreate.setToolTipText("");
        btnUserCreate.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnUserCreate.setPreferredSize(new java.awt.Dimension(45, 45));
        btnUserCreate.addActionListener(this::btnUserCreateActionPerformed);

        btnUserReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/refresh.png"))); // NOI18N
        btnUserReset.setText("Resetar");
        btnUserReset.setToolTipText("");
        btnUserReset.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnUserReset.setPreferredSize(new java.awt.Dimension(45, 45));
        btnUserReset.addActionListener(this::btnUserResetActionPerformed);

        jLabel8.setText("Nome");

        jLabel6.setText("Senha");

        jLabel7.setText("Confirmar a senha");

        jLabel3.setText("Permissão");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(729, 729, 729)
                        .addComponent(btnUserClear, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(txfId, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(txfName, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(txfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(txfPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txfPasswordConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbxPermission))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(31, 31, 31)
                                        .addComponent(jLabel3))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(btnUserCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUserDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUserReset, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txfId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txfPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txfName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel3))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txfPasswordConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxPermission, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnUserDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnUserReset, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnUserCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(btnUserClear, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tableDataUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "NOME", "USRRNAME", "WHATSAPP", "PASSWORD"
            }
        ));
        tableDataUser.setColumnSelectionAllowed(true);
        tableDataUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tableDataUserMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tableDataUser);
        tableDataUser.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (tableDataUser.getColumnModel().getColumnCount() > 0) {
            tableDataUser.getColumnModel().getColumn(0).setPreferredWidth(10);
        }

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search.png"))); // NOI18N
        jLabel9.setText("PESQUISAR");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txfTermSearch)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txfTermSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 717, Short.MAX_VALUE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                .addContainerGap())
        );

        setBounds(0, 0, 750, 533);
    }// </editor-fold>//GEN-END:initComponents

    private void cleanAndResetForm() {
        txfName.setText("");
        txfEmail.setText("");
        txfPhone.setText("");
        txfPassword.setText("");
        txfPasswordConfirm.setText("");
        txfId.setText("");

        // limpa dados de atulização
        isUpdate = false;

        // ajusta o botão da salvar
        btnUserCreate.setIcon(
                new javax.swing.ImageIcon(
                        getClass().getResource("/icons/add.png")
                )
        );
    }

    private void btnUserCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserCreateActionPerformed
        // TODO add your handling code here:

        user = new User();

        if (isUpdate) {
            user.setId(userUpdate.getId());
        }
        user.setName(txfName.getText());
        user.setEmail(txfEmail.getText());
        user.setPassword(String.copyValueOf(txfPassword.getPassword()));
        user.setPhone(txfPhone.getText().replaceAll("[^0-9]", ""));
        user.setPermission(cbxPermission.isSelected());

        UserService service = new UserService();
        String result = service.saveUser(user);

        if (result.equals("SUCESSO")) {
            JOptionPane.showMessageDialog(this, "Cliente salvo com sucesso!");
            cleanAndResetForm();
            listClientsInTable();
        } else {
            JOptionPane.showMessageDialog(this, result, "Erro de Validação", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnUserCreateActionPerformed

    private void listClientsInTable() {
        usersList = new ArrayList<>();

        model = (DefaultTableModel) tableDataUser.getModel();
        model.setNumRows(0);
        model.setColumnIdentifiers(new Object[]{"ID", "PERMISSÃO", "NOME", "EMAIL", "PHONE"});

        usersList = new UserController().list();

        if (!usersList.isEmpty()) {
            for (User u : usersList) {
                model.addRow(new Object[]{
                    u.getId(),
                    u.getPermission(),
                    u.getName(),
                    u.getEmail(),
                    Mask.maskPhone(u.getPhone()),});
                System.out.println("Usuario: " + u.toString());
            }
        }
    }

    private void btnUserClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserClearActionPerformed
        // TODO add your handling code here:
        cleanAndResetForm();

        btnUserCreate.setIcon(
                new javax.swing.ImageIcon(
                        getClass().getResource("/icons/add.png")
                )
        );
    }//GEN-LAST:event_btnUserClearActionPerformed

    private void btnUserDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserDeleteActionPerformed
        // TODO add your handling code here:
        if (userUpdate.getId() <= 0) {
            JOptionPane.showMessageDialog(this, "Selecione o usuario na tabela para excluir!", "Atenção!", JOptionPane.QUESTION_MESSAGE);
            return;
        }

        var option = JOptionPane.showInternalConfirmDialog(
                this, "Esssa alteração não tem reversão, deseja continuar?",
                "Excluir regostro",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );

        if (JOptionPane.YES_OPTION != option) {
            return;
        }

        System.out.println("Excluir usuario id: " + userUpdate.getId());
        UserService uService = new UserService();
        String result = uService.delete(userUpdate.getId());
        if(result.equals("SUCESSO")){
            JOptionPane.showMessageDialog(this, "Usuário deletado com sucesso!");
            cleanAndResetForm();
        }else{
            JOptionPane.showMessageDialog(this, "Erro de validação");
        }

    }//GEN-LAST:event_btnUserDeleteActionPerformed

    private void tableDataUserMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDataUserMouseReleased
        // TODO add your handling code here:
        setFormWithDataSelected();
        isUpdate = true;

        btnUserCreate.setIcon(
                new javax.swing.ImageIcon(
                        getClass().getResource("/icons/edit.png")
                )
        );
    }//GEN-LAST:event_tableDataUserMouseReleased

    private void btnUserResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserResetActionPerformed
        // TODO add your handling code here:
        cleanAndResetForm();

        listClientsInTable();
    }//GEN-LAST:event_btnUserResetActionPerformed

    private void setFormWithDataSelected() {
        int row = tableDataUser.getSelectedRow();

        userUpdate = new User();

        userUpdate.setId((int) tableDataUser.getModel().getValueAt(row, 0));

        boolean permission = (boolean) tableDataUser.getModel().getValueAt(row, 1);

        System.out.println("permission: " + permission);

        txfId.setText(tableDataUser.getModel().getValueAt(row, 0).toString());
        //cbxPermission.setSelected(permission);
        txfName.setText(tableDataUser.getModel().getValueAt(row, 2).toString());
        txfEmail.setText(tableDataUser.getModel().getValueAt(row, 3).toString());
        txfPhone.setText(tableDataUser.getModel().getValueAt(row, 4).toString());

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUserClear;
    private javax.swing.JButton btnUserCreate;
    private javax.swing.JButton btnUserDelete;
    private javax.swing.JButton btnUserReset;
    private javax.swing.JCheckBox cbxPermission;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableDataUser;
    private javax.swing.JTextField txfEmail;
    private javax.swing.JTextField txfId;
    private javax.swing.JTextField txfName;
    private javax.swing.JPasswordField txfPassword;
    private javax.swing.JPasswordField txfPasswordConfirm;
    private javax.swing.JFormattedTextField txfPhone;
    private javax.swing.JTextField txfTermSearch;
    // End of variables declaration//GEN-END:variables
}
