package com.ifsp.view;

import com.ifsp.dao.DB;
import java.sql.*;
import javax.swing.JOptionPane;

public class FrameLogin extends javax.swing.JFrame {

    Connection connection = null;
    PreparedStatement pst = null;
    ResultSet rst = null;
    boolean autenticado = false;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrameLogin.class.getName());

    public FrameLogin() {

        initComponents();
        txfEmail.setFocusable(true);

        connection = DB.connect();

        desableFilds(connection);

        getRootPane().setDefaultButton(btnLogin);

    }

    public void getLogin() {
        String email = txfEmail.getText().trim();
        String pass = new String(txfPassword.getPassword()).trim();

        if (email.isEmpty() || pass.isEmpty() || pass.length() < 5) {
            JOptionPane.showMessageDialog(this, "Dados de acesso inválidos!");
            return;
        }

        String sql = "select name, permission, email, password from tab_users where email = ? and password = ?";

        try {
            pst = connection.prepareStatement(sql);
            pst.setString(1, email);
            pst.setString(2, pass);

            rst = pst.executeQuery();

            if (rst.next()) {
                int permission = rst.getInt(2);
                String name = rst.getString(1);
                
                FrameHome fHome = new FrameHome();
                fHome.setVisible(true);
                JOptionPane.showMessageDialog(fHome, "Bem vindo, " + name);
                autenticado = true;
                
                fHome.lblUserLogged.setText(name + " | " + (permission == 1 ? "Administrador" : "Gestor"));
                
                if(permission == 1){
                    fHome.btnRelatory.setEnabled(true);
                    fHome.btnRegisterUser.setEnabled(true);
                }
                
                connection.close();
            } else {
                JOptionPane.showMessageDialog(this, "Usuario ou senha não encontrado");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao realizar login: " + e.getMessage());
        } finally {
            if (autenticado) {
                this.dispose();
            }
        }
    }

    public void desableFilds(Connection con) {
        if (con != null) {
            btnLogin.setEnabled(true);
            lblStatusConnectionDB.setIcon(
                    new javax.swing.ImageIcon(
                            getClass().getResource("/icons/cloud.png")
                    )
            );
        } else {
            btnLogin.setEnabled(false);
            lblStatusConnectionDB.setIcon(
                    new javax.swing.ImageIcon(
                            getClass().getResource("/icons/cloud-crossed.png")
                    )
            );
        }

        txfEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                txfEmail.selectAll();
            }
        });
        txfPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                txfPassword.selectAll();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txfEmail = new javax.swing.JTextField();
        txfPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        lblStatusConnectionDB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setText("Autenticação");

        jLabel2.setText("Usuário");

        jLabel3.setText("Senha");

        txfEmail.setText("admin");

        txfPassword.setText("admin");

        btnLogin.setText("Entrar");
        btnLogin.addActionListener(this::btnLoginActionPerformed);

        lblStatusConnectionDB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cloud-crossed.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(btnLogin)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblStatusConnectionDB))
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txfEmail, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txfPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogin)
                    .addComponent(lblStatusConnectionDB))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(327, 356));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        getLogin();
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrameLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblStatusConnectionDB;
    private javax.swing.JTextField txfEmail;
    private javax.swing.JPasswordField txfPassword;
    // End of variables declaration//GEN-END:variables
}
