/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ifsp.view;

import java.sql.Time;
import java.text.DateFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author User
 */
public class FrameHome extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrameHome.class.getName());

    /**
     * Creates new form FrameHome
     */
    public FrameHome() {
        initComponents();

        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDesktop = new javax.swing.JDesktopPane();
        lblUserLogged = new javax.swing.JLabel();
        lblDateNow = new javax.swing.JLabel();
        lblHorsNow = new javax.swing.JLabel();
        menuDesktop = new javax.swing.JMenuBar();
        btnRegister = new javax.swing.JMenu();
        btnRegisterClient = new javax.swing.JMenuItem();
        btnRegisterUser = new javax.swing.JMenuItem();
        btnRegisterOs = new javax.swing.JMenuItem();
        btnRelatory = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        btnHelp = new javax.swing.JMenu();
        btnHelpAbout = new javax.swing.JMenuItem();
        btnHelpSupport = new javax.swing.JMenuItem();
        btnSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        javax.swing.GroupLayout panelDesktopLayout = new javax.swing.GroupLayout(panelDesktop);
        panelDesktop.setLayout(panelDesktopLayout);
        panelDesktopLayout.setHorizontalGroup(
            panelDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        panelDesktopLayout.setVerticalGroup(
            panelDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lblUserLogged.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUserLogged.setText("User");

        lblDateNow.setText("...");

        lblHorsNow.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblHorsNow.setText("...");

        btnRegister.setText("Cadastro");

        btnRegisterClient.setText("Cliente");
        btnRegisterClient.addActionListener(this::btnRegisterClientActionPerformed);
        btnRegister.add(btnRegisterClient);

        btnRegisterUser.setText("Usuário");
        btnRegisterUser.setEnabled(false);
        btnRegisterUser.addActionListener(this::btnRegisterUserActionPerformed);
        btnRegister.add(btnRegisterUser);

        btnRegisterOs.setText("OS");
        btnRegister.add(btnRegisterOs);

        menuDesktop.add(btnRegister);

        btnRelatory.setText("Relatório");
        btnRelatory.setEnabled(false);

        jMenuItem4.setText("Serviços");
        btnRelatory.add(jMenuItem4);

        menuDesktop.add(btnRelatory);

        btnHelp.setText("Ajuda");

        btnHelpAbout.setText("Sobre");
        btnHelpAbout.addActionListener(this::btnHelpAboutActionPerformed);
        btnHelp.add(btnHelpAbout);

        btnHelpSupport.setText("Suporte");
        btnHelp.add(btnHelpSupport);

        menuDesktop.add(btnHelp);

        btnSair.setText("Sair");
        btnSair.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSairMouseClicked(evt);
            }
        });
        menuDesktop.add(btnSair);

        setJMenuBar(menuDesktop);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelDesktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUserLogged, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDateNow, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblHorsNow, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUserLogged)
                .addGap(18, 18, 18)
                .addComponent(lblDateNow)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblHorsNow)
                .addContainerGap(436, Short.MAX_VALUE))
            .addComponent(panelDesktop)
        );

        setSize(new java.awt.Dimension(945, 565));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterUserActionPerformed
        // TODO add your handling code here:
        FrameUser fUser = new FrameUser();
        fUser.setVisible(true);
        panelDesktop.add(fUser);
    }//GEN-LAST:event_btnRegisterUserActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        DateTimeFormatter date = DateTimeFormatter.ofPattern("MMM, dd 'de' yyyy", new Locale("pt", "BR"));
        DateTimeFormatter hors = DateTimeFormatter.ofPattern("HH:mm:ss", new Locale("pt", "BR"));
        lblDateNow.setText(LocalDateTime.now().format(date));

        Timer timer = new Timer(1000, e -> {
            lblHorsNow.setText(LocalDateTime.now().format(hors));
        });

        timer.start();
    }//GEN-LAST:event_formWindowActivated

    private void btnSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseClicked
        // TODO add your handling code here:
        int opcao = JOptionPane.showConfirmDialog(
                this,
                "Deseja realmente sair da aplicação?",
                "Fechar o sistema",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );

        if (opcao == JOptionPane.YES_OPTION) {
            FrameLogin fLogin = new FrameLogin();
            fLogin.setLocationRelativeTo(null);
            fLogin.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnSairMouseClicked

    private void btnHelpAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpAboutActionPerformed
        // TODO add your handling code here:
        FrameAbout fAbout = new FrameAbout();
        fAbout.setVisible(true);
    }//GEN-LAST:event_btnHelpAboutActionPerformed

    private void btnRegisterClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterClientActionPerformed
        // TODO add your handling code here:
        FrameClient fClient = new FrameClient();
        fClient.setVisible(true);
        panelDesktop.add(fClient);
    }//GEN-LAST:event_btnRegisterClientActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrameHome().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu btnHelp;
    private javax.swing.JMenuItem btnHelpAbout;
    private javax.swing.JMenuItem btnHelpSupport;
    private javax.swing.JMenu btnRegister;
    private javax.swing.JMenuItem btnRegisterClient;
    private javax.swing.JMenuItem btnRegisterOs;
    public static javax.swing.JMenuItem btnRegisterUser;
    public static javax.swing.JMenu btnRelatory;
    private javax.swing.JMenu btnSair;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JLabel lblDateNow;
    private javax.swing.JLabel lblHorsNow;
    public static javax.swing.JLabel lblUserLogged;
    private javax.swing.JMenuBar menuDesktop;
    private javax.swing.JDesktopPane panelDesktop;
    // End of variables declaration//GEN-END:variables
}
