# -*- coding: utf-8 -*-
"""ComplexidadeED2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lEYl7gFBtg9bPEoj7Yo1hmYsnqgMDD5W
"""

import time
import matplotlib.pyplot as plt

# Funções com diferentes complexidades
def constante(n):
    return n + 1  # O(1)

def linear(n):
    soma = 0
    for i in range(n):
        soma += i
    return soma  # O(n)

def quadratica(n):
    soma = 0
    for i in range(n):
        for j in range(n):
            soma += i * j
    return soma  # O(n²)

def logaritmica(n):
    i = 1
    count = 0
    while i < n:
        i *= 2
        count += 1
    return count  # O(log n)

def linearitmica(n):
    count = 0
    for i in range(n):
        j = 1
        while j < n:
            count += 1
            j *= 2
    return count  # O(n log n)

def exponencial(n):
    if n == 0:
        return 1
    return 2 * exponencial(n - 1)  # O(2^n)

def fatorial(n):
    if n <= 1:
        return 1
    return n * fatorial(n - 1)  # O(n!)

# Função para medir o tempo
def medir_tempo(func, entradas):
    tempos = []
    for n in entradas:
        inicio = time.time()
        func(n)
        fim = time.time()
        tempos.append(fim - inicio)
    return tempos

# Listas de entradas
entradas_normais = [10, 100, 500, 1000, 2000]
entradas_leves = list(range(1, 21))  # para exponencial e fatorial

# Medindo tempos
tempos_constante = medir_tempo(constante, entradas_normais)
tempos_log = medir_tempo(logaritmica, entradas_normais)
tempos_linear = medir_tempo(linear, entradas_normais)
tempos_quadratica = medir_tempo(quadratica, entradas_normais)
tempos_exponencial = medir_tempo(exponencial, entradas_leves)
tempos_fatorial = medir_tempo(fatorial, entradas_leves)
tempos_linearitmica = medir_tempo(linearitmica, entradas_normais)

# Plotagem
plt.figure(figsize=(12, 7))
plt.plot(entradas_normais, tempos_constante, 'ro-', label='O(1) - Constante')
plt.plot(entradas_normais, tempos_linear, 'go-', label='O(n) - Linear')
plt.plot(entradas_normais, tempos_quadratica, 'bo-', label='O(n²) - Quadrática')
plt.plot(entradas_normais, tempos_log, 'mo-', label='O(log n) - Logarítmica')
plt.plot(entradas_normais, tempos_linearitmica, 'yo-', label='O(n log n) - Linearitmica')
plt.plot(entradas_leves, tempos_exponencial, 'co-', label='O(2ⁿ) - Exponencial')
plt.plot(entradas_leves, tempos_fatorial, 'ko-', label='O(n!) - Fatorial')

plt.xlabel('Tamanho da entrada (n)')
plt.ylabel('Tempo de execução (s)')
plt.title('Tempo de execução vs Tamanho da entrada')
plt.legend()
#plt.yscale('log')
plt.grid(True)
plt.tight_layout()
plt.show()