# -*- coding: utf-8 -*-
"""OrdenaçãoPrática.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EHLua1VqNCvfvNvFFPAc6sICVJJWZhwC
"""

import random
import time
import pandas as pd
import matplotlib.pyplot as plt

# Definição de Inputs
vetor_pequeno = [random.randint(1, 100) for _ in range(10)]
vetor_medio = [random.randint(1, 10000) for _ in range(1000)]

# Algoritmos de Ordenação
def selection_sort(arr):
    arr = arr[:]
    n = len(arr)
    for i in range(n):
        min_idx = i
        for j in range(i+1, n):
            if arr[j] < arr[min_idx]:
                min_idx = j
        arr[i], arr[min_idx] = arr[min_idx], arr[i]
    return arr

# Algoritmos de Ordenação
def insertion_sort(arr):
    arr = arr[:]
    for i in range(1, len(arr)):
        key = arr[i]
        j = i - 1
        while j >= 0 and arr[j] > key:
            arr[j+1] = arr[j]
            j -= 1
        arr[j+1] = key
    return arr

# Algoritmos de Ordenação
def bubble_sort(arr):
    arr = arr[:]
    n = len(arr)
    for i in range(n):
        trocou = False
        for j in range(0, n-i-1):
            if arr[j] > arr[j+1]:
                arr[j], arr[j+1] = arr[j+1], arr[j]
                trocou = True
        if not trocou:
            break
    return arr

# Algoritmos de Ordenação
def merge_sort(arr):
    if len(arr) <= 1:
        return arr
    meio = len(arr) // 2
    esquerda = merge_sort(arr[:meio])
    direita = merge_sort(arr[meio:])
    return merge(esquerda, direita)

def merge(esq, dir):
    resultado = []
    i = j = 0
    while i < len(esq) and j < len(dir):
        if esq[i] <= dir[j]:
            resultado.append(esq[i])
            i += 1
        else:
            resultado.append(dir[j])
            j += 1
    resultado.extend(esq[i:])
    resultado.extend(dir[j:])
    return resultado

# Função para Teste dos Algoritmos
def testar_algoritmos(vetor):
    algoritmos = {
        "SelectionSort": selection_sort,
        "InsertionSort": insertion_sort,
        "BubbleSort": bubble_sort,
        "MergeSort": merge_sort
    }
    resultados = []
    for nome, func in algoritmos.items():
        inicio = time.time()
        ordenado = func(vetor)
        fim = time.time()
        resultados.append({
            "Algoritmo": nome,
            "Tempo de Execução (s)": fim - inicio,
            "10 Primeiros Números Ordenados": ordenado[:10]
        })
    return pd.DataFrame(resultados)

# Função para exibir tabela + gráfico dos resultados
def mostrar_resultados(df, titulo):
    # mostra a tabela
    print("\nTabela de resultados:")
    print(df)

    # gráfico comparando os tempos
    plt.figure(figsize=(8, 5))
    plt.bar(df["Algoritmo"], df["Tempo de Execução (s)"], color="skyblue", edgecolor="black")
    plt.xlabel("Algoritmo")
    plt.ylabel("Tempo de Execução (s)")
    plt.title(titulo)
    plt.grid(axis="y", linestyle="--", alpha=0.7)
    plt.show()

# Resultados
print("Vetores Utilizados")
print("Vetor pequeno (10 elementos):", vetor_pequeno)
print("Vetor médio (1000 elementos) - não exibido por tamanho\n")

# Testes no vetor pequeno
print("----- Testes no Vetor Pequeno -----")
df_pequeno = testar_algoritmos(vetor_pequeno)
mostrar_resultados(df_pequeno, "Tempo de Execução - Vetor Pequeno (10 elementos)")

# Testes no vetor médio
print("\n----- Testes no Vetor Médio -----")
df_medio = testar_algoritmos(vetor_medio)
mostrar_resultados(df_medio, "Tempo de Execução - Vetor Médio (1000 elementos)")